cli/aws_orbit/__main__.py
cli/aws_orbit/commands/list.py

List env fix2

---

cli/aws_orbit/commands/list.py
images/jupyter-user/extensions/jupyterlab_orbit/jupyterlab_orbit/handlers/catalog.py
images/jupyter-user/extensions/jupyterlab_orbit/jupyterlab_orbit/handlers/team.py
images/jupyter-user/extensions/jupyterlab_orbit/test/mockup/catalog.json

List cli 3

---

cli/aws_orbit/data/kubectl/apps/00-commons.yaml
cli/aws_orbit/data/kubectl/apps/02-user-service-account.yaml

add cluster read access to teams for nodes and volumes
----------

add cluster read access to teams for nodes and volumes

---

.github/workflows/jupyterlab-extensions.yml

PATH no longer contained scripts directory
----------

update PATH before executing build

---

images/landing-page/package.json
images/landing-page/yarn.lock

fix version and tested landing page worked.
----------

fix for landing page

---

images/code-build-image/Dockerfile

Add new pkgs to codebuild image

---

cli/aws_orbit/__main__.py
samples/notebooks/B-DataAnalyst/Example-3-Spark-EMR-on-EKS.ipynb

removing the init command for now
https://github.com/awslabs/aws-orbit-workbench/issues/319
----------

Disable init command

---

cli/aws_orbit/data/toolkit/template.yaml

add missing permission

---

cli/aws_orbit/data/toolkit/template.yaml
plugins/emr_on_eks/emr_on_eks/__init__.py

Ab emr patch3

---

cli/aws_orbit/remote_files/teams.py
cli/aws_orbit/services/codebuild.py
images/jupyter-user/extensions/jupyterlab_orbit/README.md
plugins/emr_on_eks/emr_on_eks/__init__.py
plugins/emr_on_eks/emr_on_eks/cdk.py

- version the plugin installs
- handle missing virtual cluster
----------

version the plugin installs, handle missing virtual cluster

---

plugins/emr_on_eks/emr_on_eks/__init__.py

fixing destroy ems_on_emr

---

cli/aws_orbit/remote_files/cdk/foundation.py

fix vpc creation

---

cli/aws_orbit/remote_files/cdk/foundation.py

fix public network to not have isolated subnets at all
----------

Fix vpc public

---

test/resources/unit/run_container_negative_test.sh
test/resources/unit/run_container_test.sh
test/resources/unit/schedule_container_test.sh

Parameterized cluster name on scripts
----------

Fix regression 1

---

demo_pipeline.yaml
samples/manifests/demo/manifest.yaml

fixing names to be different than development env

---

demo_pipeline.yaml
samples/manifests/demo/manifest.yaml

Changed demo-foundation to demo-fndn
----------

Changed demo-foundation to demo-fndn

---

cli/aws_orbit/docker.py

Tag the version of the image from context version

---

cli/requirements-dev.txt
cli/requirements.txt
images/jupyter-user/extensions/jupyterlab_orbit/requirements.txt
plugins/code_commit/requirements-dev.txt
plugins/custom_cfn/requirements-dev.txt
plugins/emr_on_eks/requirements-dev.txt
plugins/hello_world/requirements-dev.txt
plugins/redshift/requirements-dev.txt
plugins/team_script_launcher/requirements-dev.txt
scripts/upgrade_pip_packages.sh
sdk/requirements-dev.txt
sdk/requirements.txt

attempt to fix `decorator` requirements
----------

update all requirments

---

plugins/team_script_launcher/team_script_launcher/job_definition.yaml

fix resources limit

---

cli/aws_orbit/data/kubectl/apps/01-team.yaml
plugins/team_script_launcher/team_script_launcher/job_definition.yaml

required fixed for jupyterhub resources

---

images/code-build-image/Dockerfile
images/jupyter-hub/Dockerfile
images/jupyter-user/Dockerfile
images/landing-page/Dockerfile
samples/notebooks/I-Image/Example-3-gpu.ipynb

https://gitlab.aws.dev/wwcs-proserve-etip-data-analytics/software-labs/datamaker/datamaker-enterprise/-/issues/148
----------

Updated image references to images in our public ecr

---

cli/aws_orbit/remote_files/helm.py

- fix the namespace metadata on the helm charts
- make the create_team_charts_copy reusable (by plugins)
----------

fix the namespace metadata on the helm charts

---

cli/aws_orbit/remote_files/destroy.py

write_kubeconfig

---

.github/workflows/jupyterlab-extensions.yml
samples/manifests/demo/manifest.yaml

remove external provider config

---

cli/aws_orbit/remote_files/helm.py

fix version/tag on replicator image
----------

fix version/tag on replicator image

---

.gitignore
cli/aws_orbit/data/charts/env/image-replicator/values.yaml
cli/aws_orbit/remote_files/helm.py

- sts regional endpoint env var
----------

sts regional endpoint

---

cli/aws_orbit/commands/deploy.py
demo_pipeline.yaml

Condition demo destroy pipieline

---

cli/aws_orbit/commands/deploy.py

Use lowercase ascii letters for deploy_id

---

plugins/lustre/lustre/__init__.py

trying to delete of sc before installing helm

---

cli/aws_orbit/k8s.py
cli/aws_orbit/models/context.py
cli/aws_orbit/models/manifest.py
samples/manifests/minimal/dev-env.yaml
samples/manifests/plugins/dev-env-single-team.yaml
samples/manifests/plugins/dev-env-with-plugins-public.yaml
samples/manifests/plugins/dev-env-with-plugins.yaml
samples/manifests/plugins/dev-env-without-team.yaml

add k8s response logging; update defaults in sample manifest
----------

add k8s response logging; update defaults in sample manifest

---

images/code-build-image/Dockerfile

Added KFCTL

---

samples/manifests/demo/manifest.yaml

Added GPU pool

---

images/code-build-image/Dockerfile

- Added kfctl
- Added aws-iam-authenticator
----------

Add kfctl to codebuild image

---

cli/aws_orbit/models/manifest.py
images/image-replicator/src/aws_orbit_image_replicator/image_monitor.py
plugins/team_script_launcher/team_script_launcher/values.yaml

- image-replicator logging 
- team-script-launcher image
----------

image-replicator logging; team-script-launcher image

---

cli/aws_orbit/data/kubectl/apps/05-dashboard.yaml
plugins/emr_on_eks/emr_on_eks/__init__.py
plugins/emr_on_eks/emr_on_eks/cdk.py

small fix to emr_eks to to make sure policy is added
----------

Fix emr on eks

---

cli/aws_orbit/k8s.py
cli/aws_orbit/remote_files/cdk/env.py
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/index.py
cli/aws_orbit/remote_files/deploy.py

- Update Cognito userpool with a post-authentication trigger
- Wrapped try/except around fetching ingress data
----------

Cognito post auth trigger

---

cli/aws_orbit/remote_files/kubectl.py

Image pull policy typo

---

samples/manifests/demo/demo-lake-user-cfn-template.yaml
samples/manifests/demo/lake-creator-plugins.yaml
samples/manifests/demo/lake-user-plugins.yaml

Updated the demo manifest files with latest configuration from the plugins folder
----------

Fix sync samples to demo

---

README.md

Great to see how Orbit is evolving, congrats guys! 😄 
Updating the documentation link into the README.
--
----------

Updating the documentation link into the README.

---

cli/aws_orbit/data/charts/team/orbit-user/templates/configmap.yaml
cli/aws_orbit/data/kubectl/orbit-system/00-commons.yaml
cli/aws_orbit/data/kubectl/orbit-system/01-admission-controller.yaml
cli/aws_orbit/data/kubectl/teams/00-team.yaml
cli/aws_orbit/remote_files/kubectl.py
images/admission-controller/src/aws_orbit_admission_controller/__init__.py
images/admission-controller/src/aws_orbit_admission_controller/app.py
images/admission-controller/src/aws_orbit_admission_controller/namespace.py
images/admission-controller/src/aws_orbit_admission_controller/pod.py

Kf team deploy

---

cli/aws_orbit/data/charts/team/team-space/templates/pod-setting-common.yaml
cli/aws_orbit/data/charts/team/user-space/templates/poddefaults.yaml
images/admission-controller/src/aws_orbit_admission_controller/namespace.py

Kf poddefaults fix

---

cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/k8s_manage.py

- Create EFS endpoint before creating user namespace
- Remove EFS endpoint before removing user namespace
----------

User efs endpoint

---

cli/aws_orbit/data/toolkit/template.yaml
cli/aws_orbit/models/context.py
cli/aws_orbit/remote_files/teams.py

- fix helm_repository
- fix lambda layer publish
----------

fix helm_repository; fix lambda layer publish

---

cli/aws_orbit/data/toolkit/template.yaml
cli/aws_orbit/remote_files/cdk/env.py
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/index.py
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/k8s_manage.py
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/requirements.txt

- Orbit-dev-env-admin can be assumed by lambda
- Added Cognito perms to orbit-dev-env-admin-other policy
- Converted lambda to python lambda; kubernetes library is installed via requirments.txt, zip is no longer used
- Delete profile before deleting namespace
- Bug fixes and minor refactoring
----------

Fix post auth lambda perm

---

cli/aws_orbit/data/charts/team/user-space/templates/persistent.yaml
cli/aws_orbit/remote_files/kubectl.py

- hanging deploy/destroy fix
- merge conflict leftover
- user/team efs
----------

fix some hanging deployment problems

---

cli/aws_orbit/data/charts/team/team-space/templates/pod-setting-common.yaml
cli/aws_orbit/data/charts/team/user-space/templates/poddefaults.yaml
images/jupyter-user/extensions/jupyterlab_orbit/jupyterlab_orbit/handlers/team.py
sdk/aws_orbit_sdk/controller.py

Kf main ab fixes

---

cli/aws_orbit/remote_files/helm.py
plugins/code_commit/code_commit/__init__.py
plugins/code_commit/code_commit/cdk.py
plugins/custom_cfn/custom_cfn/__init__.py
plugins/emr_on_eks/emr_on_eks/__init__.py
plugins/emr_on_eks/emr_on_eks/cdk.py
plugins/hello_world/hello_world/__init__.py
plugins/hello_world/hello_world/hello_cdk.py
plugins/lustre/lustre/__init__.py
plugins/overprovisioning/overprovisioning/__init__.py
plugins/ray/ray/__init__.py
plugins/redshift/redshift/__init__.py
plugins/redshift/redshift/orbit_redshift_stack.py
plugins/sm-operator/sm-operator/__init__.py
plugins/team_script_launcher/team_script_launcher/__init__.py
plugins/team_script_launcher/team_script_launcher/templates/job_definition.yaml
plugins/team_script_launcher/team_script_launcher/values.yaml
plugins/voila/voila/__init__.py
samples/manifests/plugins/lake-creator-plugins.yaml
samples/manifests/plugins/lake-user-plugins.yaml
scripts/fix_plugins.sh

… wait for the pv changes chauncy will do and then update image.  The job deploy correctly.
----------

Update and fix test script plugin to copy the samples

---

cli/aws_orbit/data/charts/team/team-space/templates/init-efs-job.yaml
cli/aws_orbit/data/charts/team/user-space/templates/roles.yaml
cli/aws_orbit/data/kubectl/orbit-system/00-commons.yaml
cli/aws_orbit/data/kubectl/teams/00-team.yaml
cli/aws_orbit/data/kubectl/teams/01-team-rbac-role.yaml
plugins/lustre/lustre/charts/fsx_filesystem/values.yaml
plugins/lustre/lustre/charts/fsx_storageclass/values.yaml
plugins/overprovisioning/overprovisioning/values.yaml
plugins/ray/ray/values.yaml
plugins/sm-operator/sm-operator/templates/operator.yaml
plugins/sm-operator/sm-operator/values.yaml
plugins/team_script_launcher/team_script_launcher/values.yaml
plugins/voila/voila/values.yaml

fixing roles

---

images/utility-data/src/utility-data/stage_samples_data.sh
images/utility-data/src/utility-data/stage_vscode_extensions.sh
samples/manifests/plugins/lake-user-plugins.yaml

Not sure how the shebang got messed...
----------

Fixing shebang, update lake-user

---

cli/aws_orbit/models/context.py
cli/aws_orbit/remote_files/kubectl.py

fix destroy

---

images/admission-controller/src/aws_orbit_admission_controller/namespace.py

handle expired watch

---

cli/aws_orbit/remote_files/cdk/env.py
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/k8s_manage.py

- Added resource policy to allow cognito to invoke the lambda function
- Added tags to EFS endpoint when created
----------

Add Cognito Lambda resource policy

---

cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/k8s_manage.py

Fixed tag syntax

---

images/jupyter-user/codeserver_proxy/install.sh
images/jupyter-user/codeserver_proxy/start_codeserver.sh
images/jupyter-user/codeserver_proxy/startup.sh

modify jupyter-user image for vscode to leverage efs end-to-end

---

cli/aws_orbit/data/charts/team/team-space/templates/pod-setting-common.yaml
sdk/aws_orbit_sdk/controller.py

fix user identity when using controller

---

cli/aws_orbit/data/kubectl/kubeflow/kf-jupyter-launcher.yaml
samples/notebooks/Z-Tests/sanity-good.ipynb
sdk/aws_orbit_sdk/controller.py

disable grant sudo for controller for now

---

cli/aws_orbit/data/kubectl/kubeflow/kf-jupyter-launcher.yaml

fix images comment-out

---

cli/aws_orbit/data/charts/team/user-space/templates/roles.yaml
cli/aws_orbit/data/charts/team/user-space/values.yaml
cli/aws_orbit/data/kubectl/teams/02-admin-binding.yaml
cli/aws_orbit/remote_files/helm.py
images/admission-controller/src/aws_orbit_admission_controller/pod.py
plugins/ray/ray/templates/ray-cluster.yaml
plugins/sm-operator/sm-operator/templates/operator.yaml
sdk/aws_orbit_sdk/controller.py

fixes for regression notebooks

---

cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/index.py

Raise an error if email is invalid
----------

Fix cognito user no email

---

cli/aws_orbit/remote_files/kubectl.py
plugins/sm-operator/sm-operator/__init__.py

fix destroy for sagemaker and user namespaces

---

cli/aws_orbit/data/kubectl/orbit-system/01-admission-controller.yaml
cli/aws_orbit/remote_files/deploy.py
cli/aws_orbit/remote_files/kubectl.py
images/admission-controller/src/aws_orbit_admission_controller/home.py
images/admission-controller/src/aws_orbit_admission_controller/server.py
images/admission-controller/src/aws_orbit_admission_controller/static/App.css
images/admission-controller/src/aws_orbit_admission_controller/templates/index.html
images/admission-controller/src/setup.cfg
images/admission-controller/src/setup.py

Kf homepage

---

cli/aws_orbit/data/kubeflow/kfctl_aws.yaml

fix kf manifest location to our main branch

---

cli/aws_orbit/data/charts/team/team-space/templates/init-efs-job.yaml
cli/aws_orbit/data/charts/team/team-space/values.yaml
cli/aws_orbit/remote_files/helm.py

This has not been tested end-to-end yet
----------

Altering init-efs to copy vsix drivers from image

---

cli/aws_orbit/data/charts/team/team-space/templates/init-efs-job.yaml

fixing commands

---

tutorials/plugin-library.markdown

Adding redshift plugin documentation.
----------

Adding redshift plugin documentation.

---

cli/aws_orbit/data/charts/team/team-space/templates/pod-setting-common.yaml
cli/aws_orbit/remote_files/helm.py
images/orbit-controller/src/orbit_controller/namespace.py
plugins/team_script_launcher/team_script_launcher/__init__.py

fix team script to place the script in the proper chart folder
----------

fix helm install to uninstall and install.

---

cli/aws_orbit/data/kubectl/orbit-system/01a-orbit-controller.yaml

restore volume

---

plugins/team_script_launcher/team_script_launcher/__init__.py

fix release name when uninstalling

---

samples/manifests/plugins/lake-creator-plugins.yaml
samples/manifests/plugins/lake-user-plugins.yaml

Passing commands into script runner....2 plugin definitions to replace the existing copy-samples per user and team
----------

change method of copying sample data

---

cli/requirements-dev.in
cli/requirements-dev.txt
images/jupyter-user/Dockerfile
jupyterlab_orbit/requirements.txt
jupyterlab_orbit/setup.py
plugins/code_commit/requirements-dev.txt
plugins/custom_cfn/requirements-dev.txt
plugins/emr_on_eks/requirements-dev.txt
plugins/hello_world/requirements-dev.txt
plugins/lustre/requirements-dev.txt
plugins/overprovisioning/requirements-dev.txt
plugins/ray/requirements-dev.txt
plugins/redshift/requirements-dev.txt
plugins/sm-operator/requirements-dev.txt
plugins/team_script_launcher/requirements-dev.txt
plugins/voila/requirements-dev.txt
scripts/prep_build_from_source.sh
scripts/upgrade_pip_packages.sh
sdk/requirements-dev.txt
sdk/requirements.txt

- jupyterlab-orbit -> aws-orbit-jupyterlab-orbit
- update-requirements
----------

jupyterlab-orbit -> aws-orbit-jupyterlab-orbit; update-requirements

---

cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/k8s_manage.py
images/jupyter-user/codeserver_proxy/create_kubeconfig.sh
images/orbit-controller/src/orbit_controller/pod.py
plugins/emr_on_eks/emr_on_eks/__init__.py
samples/manifests/plugins/lake-user-plugins.yaml
samples/notebooks/I-Image/gpu/test-image.ipynb

small fixes

---

cli/aws_orbit/remote_files/deploy.py
cli/aws_orbit/remote_files/destroy.py

fix destroy teams

---

cli/aws_orbit/cleanup.py

Detach, instead of delete, policy from kf role
----------

Detach policy from role

---

cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/index.py
images/jupyter-user/requirements-dev.txt

edit logic for multiple envs on same cognito pool

---

cli/aws_orbit/data/charts/team/team-space/values.yaml
samples/manifests/minimal/dev-env.yaml
samples/manifests/plugins/dev-env-single-team.yaml
samples/manifests/plugins/dev-env-with-plugins-public.yaml
samples/manifests/plugins/dev-env-with-plugins.yaml

stringify account id in helm chart
----------

stringify account id in helm chart

---

cli/aws_orbit/remote_files/destroy.py

on team destroy force delete:
- jobs
- notebooks
- deployments
- statefulsets
- pods
- hyperparametertuningjobs
- trainingjobs
- batchtransformjobs
- hostingdeployments
----------

update delete mechanism

---

cli/aws_orbit/remote_files/destroy.py
cli/aws_orbit/remote_files/kubectl.py

Ab more destroy fixes

---

cli/aws_orbit/remote_files/kubectl.py

fix cni network

---

plugins/lustre/lustre/charts/team/fsx-storageclass/templates/pvc.yaml

convert chmod of luster pod to a job

---

images/jupyter-user/Dockerfile

Add smlogs to image

---

cli/aws_orbit/cleanup.py
cli/aws_orbit/remote_files/destroy.py
cli/aws_orbit/remote_files/env.py

Tear down the target group and dependencies early in the destroy env stage
https://github.com/awslabs/aws-orbit-workbench/issues/644
----------

Remove target groups early in the teardown

---

samples/manifests/plugins/dev-env-with-plugins-isolated.yaml

Isolated manifest

---

samples/notebooks/Z-Tests/run-admin-regression-notebooks.ipynb
samples/notebooks/Z-Tests/run-user-regression-notebooks.ipynb

added missing json lib

---

.github/PULL_REQUEST_TEMPLATE.md

fix issue url

---

CHANGELOG.md
cli/aws_orbit/models/context.py
cli/aws_orbit/models/manifest.py
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/index.py
samples/manifests/plugins/dev-env-with-plugins-public.yaml
samples/manifests/plugins/dev-env-with-plugins.yaml

- Add new property for SSO group
- Removed string manipulation and used sso group instead to capture user groups
----------

Add property sso group

---

CHANGELOG.md
samples/notebooks/B-DataAnalyst/Example-6-Schedule-Notebook.ipynb
samples/notebooks/B-DataAnalyst/Example-92-Delete-DemoCronJobs.ipynb

Demo cron jobs cleaner

---

CHANGELOG.md
scripts/orbit_launcher.sh

Deploys a cloudformation stack that will deploy Orbit
----------

Orbit launcher script

---

tutorials/connecting-to-redshift.markdown

Adding redshift connection md file to documentation.

---

tutorials/quick-demo-deployment.markdown

We will use a script to help simplify the demo deployment
----------

Orbit demo script; changes to reflect Kubeflow

---

tutorials/quick-demo-deployment.markdown

Removed md specific formatting

---

CHANGELOG.md
cli/aws_orbit/remote_files/cdk/foundation.py

fixed the cleanup of cognito pools

---

samples/manifests/demo/README.md

added a readme.md to samples/
Fixes #747 
----------

added a readme.md to samples/

---

cli/aws_orbit/data/toolkit/template.yaml

Update policy version

---

.gitignore
images/jupyter-user/codeserver_proxy/setup.py
samples/notebooks/M-Admin/extra_user_apps/Dockerfile
samples/notebooks/M-Admin/extra_user_apps/apps/install-all.sh

Changing the minimum required version of jupyter-server-proxy in jupyter-user and moving additional user app to the /opt/orbit location. 
https://github.com/awslabs/aws-orbit-workbench/issues/780
----------

Correcting installation of additional user apps

---

plugins/team_script_launcher/team_script_launcher/__init__.py

Changing the job wait command to kubectl

---

jupyterlab_orbit/.gitignore
jupyterlab_orbit/jupyterlab_orbit/labextension/package.json

Missing file was breaking the pypi release
----------

Unignore file causing error in Codebuild

---

plugins/lustre/lustre/__init__.py

fixed the string manipulation of lustre plugin during teams cleanup

---

samples/notebooks/I-Image/spark/Dockerfile

Spark v 3.0.2 got moved to the archive mirrors.  Update the version to 3.0.3 and change the sha
https://github.com/awslabs/aws-orbit-workbench/issues/806
----------

Upgrading spark distro version and sha

---

CHANGELOG.md
images/k8s-utilities/Dockerfile

Add a default value to Arg to avoid failure on build where the Arg isn't defined
----------

Fix unresolved arg k8s utility image

---

samples/notebooks/M-Admin/2-Image_with_apps.ipynb

Changing Image-with-apps notebook default selected kernel.

---

tutorials/plugin-development-guide.markdown

Adding plugin development with helm charts.

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/pod.py

- apply annotation to Pods to track all applied PodSettings
https://github.com/awslabs/aws-orbit-workbench/issues/823
----------

orbit/applied-podsettings annotations on Pods

---

CHANGELOG.md
cli/aws_orbit/data/kubectl/kube-system/02-cluster-autoscaler-autodiscover.yaml

increase autoscaler resource limits
----------

increase autoscaler resource limits

---

cli/aws_orbit/remote_files/kubeflow.py

Relevant error that was being addressed:
kfctl exited with error: couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 500 with message: error deleting kustomize manifests: [error evaluating kustomization manifest for knative: Timed out waiting for resource /knative-serving to be deleted. Error deleted resource is not cleaned up yet, error evaluating kustomization manifest for cert-manager: Timed out waiting for resource /cert-manager to be deleted. Error deleted resource is not cleaned up yet, error evaluating kustomization manifest for cluster-local-gateway: Timed out waiting for resource /istio-system to be deleted. Error deleted resource is not cleaned up yet, error evaluating kustomization manifest for …

Retry to delete kubeflow resources if failed due to timeout

---

tutorials/quick-demo-deployment.markdown

Added a new arg

---

scripts/orbit_launcher.sh

This is useful if needing to deploy an older version with a specific branch as manifest in main may not be compatible with an older version
----------

Added an arg to override the branch the pipeline pulls

---

samples/notebooks/I-Image/Example-2-spark.ipynb

Hardcoded image name was removed...
https://github.com/awslabs/aws-orbit-workbench/issues/781
----------

remove hardcoded image...bad developer

---

cli/aws_orbit/remote_files/destroy.py

reducing the timeperiod between deletion of userspaces
----------

reducing the timeperiod between deletion of userspaces

---

CHANGELOG.md
cli/aws_orbit/utils.py
sdk/aws_orbit_sdk/common.py

https://github.com/awslabs/aws-orbit-workbench/issues/709
----------

Added user agent field to track usage

---

samples/notebooks/I-Image/Example-2-spark.ipynb
samples/notebooks/I-Image/Example-3-gpu.ipynb
samples/notebooks/Z-Tests/run-admin-regression-notebooks.ipynb

These notebooks had an inadvertent kernel spec defined
https://github.com/awslabs/aws-orbit-workbench/issues/781
----------

removing kernel spec

---

CHANGELOG.md
cli/aws_orbit/cleanup.py

- fix cleanup when no cluster exists
----------

fix cleanup when no cluster exists

---

samples/notebooks/B-DataAnalyst/Example-8-SDK-Controller-Sched.ipynb
samples/notebooks/Z-Tests/run-user-regression-notebooks.ipynb

Adding exception handling while deleting job. 
Removing cronjob delete notebook from lake-user regression execution.
----------

Regression notebook fixes 

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/pod_default.py

remove ownerReference from userspace poddefaults
----------

remove ownerReference from userspace poddefaults

---

cli/aws_orbit/remote_files/eksctl.py

started locking eks cluster versions via eksctl
----------

started locking eks cluster versions via eksctl

---

plugins/custom_cfn/custom_cfn/cdk.py

Changing Custom cfn yaml loader to safe load.

---

cli/aws_orbit/remote_files/destroy.py

Cleaning orbit teams using multi threaded approach.

---

samples/manifests/plugins/nightly-env-with-plugins-isolated.yaml
samples/manifests/plugins/nightly-env-with-plugins.yaml

Manifest for ci cd

---

CHANGELOG.md
cli/aws_orbit/models/manifest.py

fix regex on yaml parameter replacement

---

CHANGELOG.md
cli/aws_orbit/commands/deploy.py
cli/aws_orbit/models/manifest.py

orbit manifest validator
----------

Feature - orbit manifest validator

---

samples/manifests/plugins/cicd-full-env-with-plugins.yaml
samples/manifests/plugins/cicd-full-iso-env-with-plugins.yaml
samples/manifests/plugins/cicd-iter-env-with-plugins.yaml
samples/manifests/plugins/cicd-iter-iso-env-with-plugins.yaml

Created manifest for ci/cd, leaving original plugin files intact
----------

Manifest for CI/CD

---

cli/aws_orbit/messages.py

Fixed typing

---

.github/ISSUE_TEMPLATE/config.yaml

Disabling blank issue forces to use template

---

cli/aws_orbit/data/kubectl/teams/00-team.yaml
plugins/redshift/redshift/orbit_redshift_stack.py
samples/notebooks/I-Image/Example-3-gpu.ipynb

Fixes to regression tests and code 
https://github.com/awslabs/aws-orbit-workbench/issues/930
----------

fixes based on regression tests

---

CHANGELOG.md
plugins/redshift/redshift/lambda_sources/redshift_db_creator/redshift_functions.py
sdk/aws_orbit_sdk/database.py

Redshift plugin - Describe clusters specific to env and team

---

samples/manifests/demo/manifest.yaml

Add codeartifact en var
----------

Add codeartifact env var

---

demo_pipeline.yaml

Missing quotes

---

samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb

Conflicting metadata caused the notebook to not open

---

samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb

Removed empty cell

---

samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb

Lake-creator needed dynamic vars
https://github.com/awslabs/aws-orbit-workbench/issues/928
----------

regression fixes

---

samples/notebooks/B-DataAnalyst/Example-91-LakeFormation-Security.ipynb

Variable substitution

---

samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb
samples/notebooks/I-Image/Example-3-gpu.ipynb
sdk/aws_orbit_sdk/magics/database.py

Magics for DDL needed logic, lake-user gpu podsettings had typo
https://github.com/awslabs/aws-orbit-workbench/issues/928
----------

Fix/regression 1.3.0

---

samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb

Exception is thrown when trying to remove permissions that the resources doesnt have
----------

Catch exception when trying to revoke perm that dont exist

---

CHANGELOG.md
samples/notebooks/B-DataAnalyst/Example-6-Schedule-Notebook.ipynb

A notebook had referenced git:// as a source path....we aren't doing gitops (yet)
https://github.com/awslabs/aws-orbit-workbench/issues/946
----------

clean up regressions

---

CHANGELOG.md
samples/notebooks/M-Admin/extra_user_apps/apps/lens/install.sh
samples/notebooks/M-Admin/extra_user_apps/apps/lens/start_lens.sh

Adding lens support to jupyter-user-with-apps image
https://github.com/awslabs/aws-orbit-workbench/issues/975
----------

lens support in jupyter-user-with-apps

---

plugins/team_script_launcher/team_script_launcher/__init__.py

Handling team_script_launcher destroy hook job wait errors

---

samples/manifests/demo/lake-creator-plugins.yaml
samples/manifests/regression/lake-creator-plugins-iso.yaml
samples/notebooks/A-LakeCreator/Example-1-Build-Lake.ipynb
samples/notebooks/A-LakeCreator/Example-3-Load-Database-Athena.ipynb
samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb
samples/notebooks/B-DataAnalyst/Example-1-SQL-Analysis-Athena.ipynb
samples/notebooks/B-DataAnalyst/Example-2-SQL-Analysis-RedshiftSpectrum.ipynb
samples/notebooks/B-DataAnalyst/Example-6-Schedule-Notebook.ipynb
samples/notebooks/B-DataAnalyst/Example-91-LakeFormation-Security.ipynb

Athena does not support database or table names that contain a hyphen in it. And our isolated env name do contain a hyphen. 
----------

Removed hyphen from db name

---

cli/aws_orbit/services/eks.py

Check the status of the eks cluster before attempting to delete fargate profile
----------

Fix describe cluster before deleteing profile

---

CHANGELOG.md
cli/aws_orbit/services/ecr.py
samples/notebooks/Z-Tests/run-admin-regression-notebooks.ipynb

LakeFormation for Admin needed to be added back to notebooks to run
https://github.com/awslabs/aws-orbit-workbench/issues/946
----------

Fix/regression 1.3.0 ongoing

---

CHANGELOG.md
samples/notebooks/A-LakeCreator/Example-1-Build-Lake.ipynb
samples/notebooks/Z-Tests/run-admin-regression-notebooks.ipynb
samples/notebooks/Z-Tests/run-user-regression-notebooks.ipynb

Lakeformation doesn't have VPC endpoint support.  Removing LF tests when the env ends in '-iso'
https://github.com/awslabs/aws-orbit-workbench/issues/946
----------

removing lakeformation tests from isolated envs

---

samples/notebooks/B-DataAnalyst/Example-8-SDK-Controller-Sched.ipynb

Missing replace() on string. Athena doesnt like "-"

---

cli/aws_orbit/services/eks.py

Logging for debugging

---

CHANGELOG.md
cli/aws_orbit/data/kubectl/teams/00-team.yaml

fixed the unresolved parameter references
----------

fixed the unresolved parameter references

---

samples/notebooks/B-DataAnalyst/Example-1-SQL-Analysis-Athena.ipynb

Change var name so it doesnt overwrite dataframe object

---

images/orbit-controller/src/orbit_controller/webhooks/imagereplication_pod_webhook.py

fix for NoneType on init or regular containers
----------

fix for NoneType on init or regular containers

---

.github/workflows/static-checking.yml
sdk/aws_orbit_sdk/common.py
sdk/aws_orbit_sdk/controller.py
sdk/aws_orbit_sdk/database.py
sdk/aws_orbit_sdk/emr.py
sdk/aws_orbit_sdk/glue_catalog.py
sdk/aws_orbit_sdk/json.py
sdk/aws_orbit_sdk/magics/database.py
sdk/aws_orbit_sdk/magics/orbit.py
sdk/aws_orbit_sdk/transformations.py

- fix type checking
- clean up make_pod
https://github.com/awslabs/aws-orbit-workbench/issues/1012
----------

fix type checking and clean up make_pod

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/webhooks/imagereplication_pod_webhook.py

- fix patch returned when no work is done
https://github.com/awslabs/aws-orbit-workbench/issues/1023
----------

fix patch returned when no work is done

---

samples/notebooks/B-DataAnalyst/Example-91-LakeFormation-Security.ipynb

Cleaning lake user lf notebook

---

plugins/redshift/redshift/orbit_redshift_stack.py

added a missing reference to lambda exec role

---

cli/aws_orbit/services/eks.py

Check fargate profile state before attempting to destroy
----------

Fargate profile destroy handler

---

CHANGELOG.md
cli/aws_orbit/data/kubectl/orbit-system/commons/base/00a-commons.yaml

added schedule (cron string) to orbitjob CRD
https://github.com/awslabs/aws-orbit-workbench/issues/1062
----------

added schedule (cron string) to orbitjob CRD

---

cli/aws_orbit/data/kubectl/orbit-system/commons/base/00a-commons.yaml
images/orbit-controller/src/orbit_controller/operators/orbitjob_operator.py
test/regressions/test_lake_admin.py

This PR relays K8s job status to OrbitJob so pytest framework can re-use the monitoring status to decide if the tests have been successful/failed.
This PR also includes `test_lake_admin` test module from `Sreeram` which was used to test the integration between the OrbitJob status and pytest execution
#1046 
----------

Feature/OrbitJob Monitoring

---

CHANGELOG.md
cli/requirements-dev.in
samples/notebooks/A-LakeCreator/Example-2-Extract-Files.ipynb
samples/notebooks/A-LakeCreator/Example-4-LakeFormation-Secured-DB.ipynb
samples/notebooks/M-Admin/4-LakeFormation-Account-Settings.ipynb
test/regressions/common_utils.py
test/regressions/custom_resources.py
test/regressions/pytest.ini
test/regressions/scripts/pytest-lake-admin.sh
test/regressions/scripts/pytest-lake-creator-multithreaded.sh
test/regressions/scripts/pytest-lake-creator.sh
test/regressions/scripts/pytest-lake-user.sh
test/regressions/test_lake_admin.py
test/regressions/test_lake_creator.py
test/regressions/test_lake_user.py

Orbit PyTest Regression tests.

---

cli/aws_orbit/services/codebuild.py
images/orbit-controller/src/orbit_controller/utils/imagereplication_utils.py

changed the storage driver and narrowed down the connection to localhost
#1066 
----------

changed the storage driver and narrowed down the connection to localhost

---

samples/manifests/trial/demo-lake-admin-cfn-template.yaml
samples/manifests/trial/demo-lake-creator-cfn-template.yaml
samples/manifests/trial/demo-lake-user-cfn-template.yaml
samples/manifests/trial/lake-admin-plugins.yaml
samples/manifests/trial/lake-creator-plugins.yaml
samples/manifests/trial/lake-user-plugins.yaml
samples/manifests/trial/trial-manifest.yaml

Adding location and artifacts to support one-click-deploys
----------

initial start to one-click-deploy

---

CHANGELOG.md
images/utility-data/Dockerfile
sdk/aws_orbit_sdk/controller.py

Fixing Orbit SDK OrbitJob status check 

---

cli/aws_orbit/services/codebuild.py

drop storage-opt size

---

CHANGELOG.md
cli/aws_orbit/remote_files/cdk/team_builders/iam.py

sleep and retry the ListPolicyTag api call after being throttled in destroy teams
----------

Retry list policy tag call after throttling

---

.github/workflows/static-checking.yml

Added feature/remote-toolkit to static checking

---

.github/workflows/static-checking.yml

Added feature/remote-toolkit to static checking (#1200)

---

test/regressions/test_lake_admin.py
test/regressions/test_lake_user.py

Increased the waiting for the job to create timeout from 1min to 2mins

---

cli/aws_orbit/remote_files/__init__.py

fixed the relative path
----------

fixed the relative path

---

cli/aws_orbit/remote_files/__init__.py
samples/manifests/regression/lake-admin-plugins-iso.yaml
samples/manifests/regression/lake-admin-plugins.yaml
samples/manifests/regression/lake-creator-plugins-iso.yaml
samples/manifests/regression/lake-creator-plugins.yaml
samples/manifests/regression/lake-user-plugins-iso.yaml
samples/manifests/regression/lake-user-plugins.yaml

reverting the fix related to path of modules
----------

reverting the fix related to path of modules and fixed regression manifests

---

images/jupyter-user/Dockerfile

Installing `slrt` in jupyter image
----------

installing slrt in jupyter

---

cli/aws_orbit/data/toolkit/template.yaml

fixed the hardcoded region/account info

---

cli/aws_orbit/__main__.py
cli/aws_orbit/commands/destroy.py
cli/aws_orbit/remote_files/destroy.py

added a command to destroy images from ecr repo

---

cli/aws_orbit/remote_files/cdk/env.py

pointed to the new naming format of codeartifact domain

---

cli/aws_orbit/commands/delete.py
cli/aws_orbit/commands/deploy.py
cli/aws_orbit/commands/destroy.py
cli/aws_orbit/remote_files/cdk/team_builders/iam.py
cli/aws_orbit/remote_files/delete.py
cli/aws_orbit/remote_files/deploy.py
cli/aws_orbit/remote_files/destroy.py

Adding toolkit annotations to image and credentials CLI

---

CHANGELOG.md
images/jupyter-user/Dockerfile
samples/manifests/regression/cicd-full-env-with-path-plugins.yaml
samples/manifests/regression/cicd-full-env-with-plugins.yaml
samples/manifests/regression/cicd-full-iso-env-with-plugins.yaml
samples/manifests/regression/cicd-iter-env-with-plugins.yaml
samples/manifests/regression/cicd-iter-iso-env-with-plugins.yaml
samples/manifests/regression/dev-env-single-team.yaml
samples/manifests/regression/dev-env-without-team.yaml
test/regressions/test_lake_admin.py

Regression build image validate

---

images/jupyter-user/Dockerfile

Updated version

---

CHANGELOG.md
cli/aws_orbit/docker.py
cli/aws_orbit/models/manifest.py
cli/aws_orbit/remote_files/deploy.py
images/jupyter-user/Dockerfile
samples/manifests/minimal/dev-env.yaml
samples/manifests/plugins/dev-env-with-plugins.yaml
samples/manifests/regression/cicd-full-env-with-path-plugins.yaml
samples/manifests/regression/cicd-full-env-with-plugins.yaml
samples/manifests/regression/cicd-full-iso-env-with-plugins.yaml
samples/manifests/regression/cicd-iter-env-with-plugins.yaml
samples/manifests/regression/cicd-iter-iso-env-with-plugins.yaml

Correct orbit deploy images to update SSM.
https://github.com/awslabs/aws-orbit-workbench/issues/1255
https://github.com/awslabs/aws-orbit-workbench/issues/1260
https://github.com/awslabs/aws-orbit-workbench/issues/1261
https://github.com/awslabs/aws-orbit-workbench/issues/1262
----------

FIX - deploy images updates SSM

---

cli/aws_orbit/__main__.py
cli/aws_orbit/commands/destroy.py

destroying env toolkit outside of env scope
#1251
----------

destroying env toolkit outside of env scope

---

trial/trial_pipeline_cfn.yaml

Changed the version of orbit in the one-click template
https://github.com/awslabs/aws-orbit-workbench/issues/TBD
----------

updating the version on one-click

---

cli/aws_orbit/commands/list.py
cli/aws_orbit/utils.py

refactored orbit list image command.
```
$ orbit list image -e dev-env
Available docker images into the dev-env env:
> k8s-utilities
> utility-data
> jupyter-user
> orbit-controller
```
#1244 
----------

refactored orbit list image command

---

cli/aws_orbit/remote_files/deploy.py

The SSM is not getting updated properly when building images individually (in parallel) (ref `orbit deploy images -i<image-name> -f <manifest.yaml>` )
https://github.com/awslabs/aws-orbit-workbench/issues/1273
----------

fix/image-creation-logic writing to SSM

---

cli/aws_orbit/__main__.py
cli/aws_orbit/commands/deploy.py
cli/aws_orbit/models/context.py
cli/aws_orbit/models/manifest.py
samples/manifests/minimal/dev-env.yaml
samples/manifests/plugins/dev-env-with-plugins.yaml
samples/manifests/regression/cicd-full-env-with-path-plugins.yaml
samples/manifests/regression/cicd-full-env-with-plugins.yaml
samples/manifests/regression/cicd-full-iso-env-with-plugins.yaml
samples/manifests/regression/cicd-iter-env-with-plugins.yaml
samples/manifests/regression/cicd-iter-iso-env-with-plugins.yaml
samples/manifests/regression/dev-env-single-team.yaml
samples/manifests/regression/dev-env-with-plugins-public.yaml
samples/manifests/regression/dev-env-without-team.yaml

Cleaning CA attributes from orbit cli options and models

---

.gitignore
CHANGELOG.md
cli/aws_orbit/data/toolkit/template.yaml
cli/aws_orbit/models/context.py
cli/aws_orbit/remote_files/__init__.py
cli/aws_orbit/remote_files/cdk/env.py
cli/aws_orbit/remote_files/cdk/team_builders/iam.py
cli/aws_orbit/remote_files/delete.py
cli/aws_orbit/remote_files/deploy.py
cli/aws_orbit/remote_files/destroy.py
cli/aws_orbit/toolkit.py
images/jupyter-user/Dockerfile
images/jupyter-user/build.sh
images/jupyter-user/bundle.sh

Software-toolkit is replaced by AWS-CodeSeeder
https://github.com/awslabs/aws-orbit-workbench/issues/1268
----------

adding support for codeseeder, remove remotectl

---

cli/aws_orbit/remote_files/__init__.py

fix for renamed  aws-codeseeder classes
----------

fix for renamed  aws-codeseeder classes

---

cli/aws_orbit/services/ssm.py
images/jupyter-user/Dockerfile

Retry if encounter SSM error TooManyUpdates 
----------

Fix ssm error too many updates

---

cli/aws_orbit/models/manifest.py
cli/aws_orbit/remote_files/__init__.py
cli/setup.py

- install_requires codeseeder
- code-build-base to codeseeder
----------

install_requires codeseeder; code-build-base to codeseeder

---

CHANGELOG.md
cli/aws_orbit/models/changeset.py
cli/aws_orbit/remote_files/__init__.py
cli/aws_orbit/remote_files/cdk/team.py
cli/aws_orbit/remote_files/deploy.py
cli/aws_orbit/services/s3.py
cli/aws_orbit/services/ssm.py

Added support for S3 object puts
Moved changeset SSM to S3
Added recursion for deletion of SSM parameters (more than 10 at a time)
Increase build timeout
----------

FIX-allow for creation and destruction of 20+ teams

---

samples/notebooks/A-LakeCreator/Example-1-Build-Lake.ipynb

The job spec errors that it is received a boolean where it was expecting a string
----------

Changed boolean values to str

---

CHANGELOG.md
cli/aws_orbit/remote_files/cdk/lambda_sources/cognito_post_authentication/k8s_manage.py

Update the lambda that creates userspaces to check for team EFS or shared EFS
----------

fix/look for TeamEFS override when creating user namespaces

---

CHANGELOG.md
plugins/sm-operator/sm-operator/__init__.py
plugins/sm-operator/sm-operator/values.yaml

Added mapping of region to sm-operator image, updated chart to reflect this mapping
https://github.com/awslabs/aws-orbit-workbench/issues/1307
----------

adding ability to use region-specific images for sm-operator

---

CHANGELOG.md
samples/notebooks/H-Model-Development/Example-5-SageMaker-on-EKS-xgboost_mnist.ipynb

Updated the sm-operator notebook to properly parse mnist data
https://github.com/awslabs/aws-orbit-workbench/issues/1310
----------

updated notebook

---

images/jupyter-user/requirements.txt

OS Command Injection in cookiecutter #33

fix dependabot cookiecutter version

---

cli/requirements-dev.txt

Update `notebook` version in requirements-dev
https://github.com/awslabs/aws-orbit-workbench/security/dependabot/34
----------

update `notebook` version

---

images/jupyter-user/requirements.txt

Upgraded sagemaker lib, it was old and its own dependencies were causing errors
----------

Upgraded sagemaker

---

images/jupyter-user/requirements.txt

Fixed conflicting dependencies found after upgrading sagemaker
----------

Upgrading dependencies that break other dependencies

---

demo_pipeline.yaml

encrypting the artifacts bucket
----------

encrypting the artifacts bucket
