awslabs/aws-orbit-workbench

samples/notebooks/I-Image/Example-1-simple.ipynb
samples/notebooks/I-Image/Example-2-spark.ipynb

These notebooks have hardcoded environment params that cause tests to fail if your foundation is not named dev-env
----------

removing hardcoded env params

---

cli/aws_orbit/models/context.py
cli/aws_orbit/remote_files/cdk/team_builders/iam.py

- always set install_ssm_agent to manifest value
- fix teams toolkit bucket permissions
----------

always set to manifest value; fix teams permissions

---

cli/aws_orbit/remote_files/cdk/team_builders/iam.py
cli/aws_orbit/remote_files/kubectl.py

- rollback toolkit permissions
- use utils for template on ssm manifest
----------

rollback toolkit permissions; use utils for template on ssm manifest

---

cli/aws_orbit/models/context.py
cli/aws_orbit/models/manifest.py

Null's out any env var whose injection value is empty instead of giving an empty string value
Include other external provider configuration if a external provider is provided
----------

Handle null cognito external config

---

plugins/sm-operator/sm-operator/values.yaml

Title says it all - sagemaker-operater dependency image in our public ECR, this is a change to reference that repo
----------

changing references to sm-operator image to our public repo

---

images/admission-controller/src/aws_orbit_admission_controller/pod.py

…s fixed
Temporarily retrieve all pod_settings on each request until caching is fixed
----------

retrieve all pod_settings on each request

---

plugins/code_commit/requirements-dev.txt
plugins/custom_cfn/requirements-dev.txt
plugins/emr_on_eks/requirements-dev.txt
plugins/hello_world/requirements-dev.txt
plugins/lustre/requirements-dev.txt
plugins/overprovisioning/requirements-dev.txt
plugins/ray/requirements-dev.txt
plugins/redshift/requirements-dev.txt
plugins/sm-operator/requirements-dev.txt
plugins/team_script_launcher/requirements-dev.txt
plugins/voila/requirements-dev.txt

Impact
When provided with a URL containing many @ characters in the authority component the authority regular expression exhibits catastrophic backtracking causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.
Patches
The issue has been fixed in urllib3 v1.26.5.
CVE-2021-33503
----------

CVE-2021-33503 - patch urllib3

---

images/orbit-controller/src/orbit_controller/pod.py
images/orbit-controller/src/orbit_controller/podsetting.py
plugins/lustre/lustre/charts/team/fsx-storageclass/templates/podsettings.yaml

move podsetting watch label_selector to client rather than api
----------

move label_selector to client rather than api

---

cli/aws_orbit/services/ec2.py

Catch the exception if the parameter type is not what the function expects. Ticket below
https://github.com/awslabs/aws-orbit-workbench/issues/642
----------

Bug fix - revoke ingress param validation error

---

cli/aws_orbit/remote_files/eksctl.py

changed instanceType from t3 to m5 cuz t3 doesnt have trunk support yet
Fixes #679 
----------

changed instanceType from t3 to m5 cuz t3 doesnt have trunk support yet

---

samples/manifests/demo/lake-creator-plugins.yaml

Looks like overprovisioning plugin was moved to admin...removing the one in creator
----------

remove overprovisioning from creator as it is in admin now

---

cli/aws_orbit/remote_files/deploy.py

…ncreasing the refresh token to 90 days.  Thats the longest that the pod can be running in without re-login.
https://github.com/awslabs/aws-orbit-workbench/issues/708
----------

fixing refresh token time

---

cli/aws_orbit/remote_files/cdk/team_builders/iam.py
samples/notebooks/Z-Tests/run-admin-regression-notebooks.ipynb
samples/notebooks/Z-Tests/run-user-regression-notebooks.ipynb

This change will add ability to drop alerts to internal slack channel whenever a driver regression notebook fails.
Fixes #695 
----------

added ability to send notebook failure alerts to internal slack channel

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/pod.py

- podsetting-pod-modifier not applying resources to pods
----------

podsetting-pod-modifier not applying resources to pods

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/image_replication.py
images/orbit-controller/src/orbit_controller/namespace.py
images/orbit-controller/src/orbit_controller/pod_default.py
images/orbit-controller/src/orbit_controller/pod_setting.py

- reset resource_version when watch dies gracefully
https://github.com/awslabs/aws-orbit-workbench/issues/840
----------

reset resource_version when watch dies gracefully

---

samples/manifests/plugins/lake-admin-plugins.yaml
samples/manifests/plugins/lake-user-plugins.yaml

Removed Ray and Overprovisioning plugins...
For Ref:
-   PluginId: ray
Module: ray
Parameters:
workers: 3
release_tag: 1.3.0
-   PluginId: overprovisioning1
Module: overprovisioning
Parameters:
replicas: 3
cpu: 2
memory: 4G
https://github.com/awslabs/aws-orbit-workbench/issues/781
----------

removing ray and overprovisioning plugins for now

---

CHANGELOG.md
plugins/ray/ray/values.yaml
samples/manifests/demo/manifest.yaml

Team specific security group was missing on the ray head, further causing timeout issues for the traffic coming into the `branch-eni` of ray head from worker pods.
#677 
----------

fixed the issue which caused the ray workers not to join ray head

---

CHANGELOG.md
plugins/overprovisioning/overprovisioning/__init__.py
plugins/overprovisioning/overprovisioning/values.yaml
samples/manifests/plugins/lake-admin-plugins.yaml

Refactor overprovisioning to support nodegroups in nodeSelector.  Re-implement on the admin namespace and have example for GPU nodegroups
https://github.com/awslabs/aws-orbit-workbench/issues/646
----------

Fix/overprovisioning plugin to run on node-groups

---

CHANGELOG.md
cli/aws_orbit/remote_files/cdk/env.py

ServiceAccount IAM role needs access to perform: fsx:TagResource on resource: arn:aws:fsx:*:***:file-system/* to allow dynamic FSX based PV creation via PVC claim and StorageClass.
----------

Adding fsx tagging access for PVC based PV creation dynamically

---

CHANGELOG.md
cli/aws_orbit/remote_files/kubectl.py

Force the al-controller to use env nodes via nodeSelector applied via a patch
https://github.com/awslabs/aws-orbit-workbench/issues/896
----------

force alb-controller onto env nodes

---

plugins/custom_cfn/custom_cfn/__init__.py

Destroy teams references lake-buckets with region in the name. That doesnt exist, so redeployment of teams fails because the buckets exists because they were not destroyed in destroy teams
----------

Removed region from bucket reference

---

CHANGELOG.md
cli/aws_orbit/remote_files/kubectl.py

teams needed the region populated from the context
https://github.com/awslabs/aws-orbit-workbench/issues/930
----------

adding region from context when deploying teams

---

plugins/redshift/redshift/__init__.py

The destroy redshift function was trying to remove all clusters, even those outside of it's env. This caused it to look for clusters that didnt exist due to the namespaces of other env clusters
----------

Destroy cluster only related to the destroy's env

---

images/jupyter-user/python-utils/notebook_runner.py
images/jupyter-user/requirements.txt

Feature allowing CodeCommit based files available to the job pod container file system. The CodeCommit repo is cloned to container /tmp/* path.
----------

Feature - Copy CodeCommit plugin based notebooks to scheduled container executions

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/controllers/namespace_controller.py

fix podsettings filter when copying into user namespace
----------

update index of team podsettings used when copying

---

CHANGELOG.md
images/orbit-controller/src/orbit_controller/operators/orbitjob_operator.py

fixed the orbitjob to use the status object, and not job index
#1064 
----------

fixed the orbitjob to use the status object, and not job index

---

cli/aws_orbit/__main__.py
cli/aws_orbit/commands/deploy.py
cli/aws_orbit/remote_files/deploy.py

Adding back in support for manifests for build images
https://github.com/awslabs/aws-orbit-workbench/issues/1229
----------

REFACTOR - adding manifest support for deploy  images

---

cli/aws_orbit/remote_files/deploy.py

When images are built, it is multithreaded AND supports building a single image at a time.  We need to make sure the thread / context is properly updated with the latest SSM info BEFORE writing changes back
https://github.com/awslabs/aws-orbit-workbench/issues/TO_BE_DEFINED
----------

FIX - logic for updating SSM when building images via multithreading

---

CHANGELOG.md
cli/aws_orbit/remote_files/eksctl.py
cli/aws_orbit/services/iam.py

When destroying the env, delete the OIDC from the trust policy (that the toolkit manages) so that we don't hit the limit of the policy
https://github.com/awslabs/aws-orbit-workbench/issues/1288
----------

fix/remove cluster OIDC from admin trust when deleting env

---

CHANGELOG.md
samples/notebooks/H-Model-Development/Example-5-SageMaker-on-EKS-xgboost_mnist.ipynb

Fetch XGBoost image based off region from sagemaker utilities
https://github.com/awslabs/aws-orbit-workbench/issues/1312
----------

adding dynamic selection of xgboost image based on region

---

images/jupyter-user/requirements-dev.txt
images/jupyter-user/requirements.txt

the dependabot issue version for cookiecutter should be in requrements-dev, not requirements

putting dev requirements in proper place

---

CHANGELOG.md
cli/remote-requirements.txt

version lock the **jsii** and **constructs** libraries in `cli/remote-requirements.txt` to eliminate cdk hang.
https://github.com/awslabs/aws-orbit-workbench/issues/1330
----------

ISSUE-1330: version lock jsii and constructs in remote-requirements.txt

---

CHANGELOG.md
cli/aws_orbit/data/init/default-env-manifest.yaml

`orbit init` command creates a manifest that's missing a default compute node group. this PR adds a node-group called **primary-compute** as an example, with autoscaling to 0
----------

add a node-group to sample manifest created by init command

---

CHANGELOG.md
cli/aws_orbit/data/init/default-env-manifest.yaml
cli/aws_orbit/remote_files/kubectl.py

When deploying in an isolated environment, deployment failed to check if the SSM Agent was installed before restarting the SSM Agent DaemonSet. Added check and added `InstallSsmAgent: true` to init manifest as a best practice recommendation.
https://github.com/awslabs/aws-orbit-workbench/issues/1335
----------

ISSUE-1335: Fix/missing ssm agent check
